version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: alitrucks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/alitrucks
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      # Volume for file uploads (images, documents, etc.)
      - uploads_data:/app/public/uploads
      # Optional: Volume for logs
      - app_logs:/app/logs
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:
  uploads_data:
  app_logs:

networks:
  app-network:
    driver: bridge